schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "blender_rich_presence_plus"
version = "1.2.1"
name = "Blender Rich Presence Plus"
tagline = "Fully customizable Discord Rich Presence for Blender"
maintainer = "Haggets <contact@haggets.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://extensions.haggets.com"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["User Interface", "Tracking"]

blender_version_min = "2.83.0"
# Optional: Blender version that the extension does not support, earlier versions are supported.
# This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = ["SPDX:MIT"]
